language: scala
sudo: false
branches:
  only:
    - master
jdk:
  -openjdk9
scala:
  - 2.12.6
script:
  - sbt test
cache:
  directories:
    - $HOME/.sbt
before_cache:
  - find $HOME/.sbt        -name "*.lock"               -print -delete